In [1]:
#Data Cleaning
import pandas as pd
import os
import numpy as np

#Data is saved on diffrent CSVs for each city
#To make things easier, we can combine the data into one dataframe
dfs = []
for file in os.listdir("data"):
    df = pd.read_csv(os.path.join("data", file))
    df["City"] = file.replace(".csv", "")
    dfs.append(df)
df = pd.concat(dfs)

#As documented on kaggle, 9 implies that this information was not found for a home.
#Therefore we replaced all 9s with np.nan as is standard for empty values

temp = df["No. of Bedrooms"].copy()
df = df.applymap(lambda x: (np.nan if x == 9  else  x))
df["No. of Bedrooms"] = temp
df

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator,City
0,30000000,3340,JP Nagar Phase 1,4,0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
3,8358000,1675,Doddanekundi,3,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
4,6845000,1670,Kengeri,3,0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7714,14500000,1180,Mira Road East,2,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mumbai
7715,14500000,530,Naigaon East,1,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mumbai
7716,4100000,700,Shirgaon,1,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mumbai
7717,2750000,995,Mira Road East,2,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mumbai
7718,2750000,1020,Mira Road East,2,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mumbai

In [2]:
#Given this implies that a given row with a nan values likely contains nan values, we can simply drop all rows with nan
cleaned_df = df[~df.isnull().any(axis=1)]
cleaned_df

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator,City
0,30000000,3340,JP Nagar Phase 1,4,0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
3,8358000,1675,Doddanekundi,3,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
4,6845000,1670,Kengeri,3,0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1393,62000000,1450,Worli,3,0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Mumbai
1394,2500000,540,Virar East,1,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Mumbai
1395,19000000,1267,Belapur,3,1,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Mumbai
1396,14900000,1245,Airoli,2,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Mumbai
1397,14000000,1183,Airoli,2,0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Mumbai

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import numpy as np
#import plotly.figure_factory as ff
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

df = cleaned_df

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

## Baseline

In [5]:
import sklearn

## Given a possible pipeline, get the score metrics for it
def score_suite(pipe, X_test, y_test):
    y_pred = pipe.predict(X_test)
    return (
        pipe.score(X_test, y_test),
        sklearn.metrics.mean_squared_error(y_test, y_pred),
    )

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    cleaned_df.drop("Price", axis=1), 
    cleaned_df["Price"], 
    test_size=0.33, 
    random_state=42
)

In [7]:
ct = ColumnTransformer(
    [
        ("Location_One_Hot",  OneHotEncoder(handle_unknown="ignore"), ["Location", "City"]),
    ],
    remainder="passthrough"
)
base_pipe = Pipeline([('transformers', ct), ('LR', LinearRegression())])
base_pipe.fit(X_train, y_train)
score_suite(base_pipe, X_test, y_test)

(0.5710465617879293, 71646545941943.73)

## Model Building

In [8]:
from tqdm import tqdm
def nested_cv_sklearnModels(model_param_dict, X_train, y_train):
    inner_cv_results = {}
    for model in tqdm(model_param_dict):
        model_data = model_param_dict[model]
        inner_cv = sklearn.model_selection.GridSearchCV(model_data["estimator"],model_data["params"])
        inner_cv.fit(X_train, y_train)
        inner_cv_results[model] = inner_cv.cv_results_
    return inner_cv_results

In [11]:
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

ct = ColumnTransformer(
    [
        ("Location_One_Hot",  OneHotEncoder(handle_unknown="ignore"), ["Location", "City"]),
    ],
    remainder="passthrough"
)

model_param_dict = {}

model_param_dict["base"] = {
    "estimator": base_pipe,
    "params": {
    }  
}    


#https://scikit-learn.org/stable/tutorial/statistical_inference/putting_together.html
#See above for why __
model_param_dict["SVR"] = {
    "estimator": Pipeline([('transformers', ct), ('SVR', SVR())]),
    "params": {
        "SVR__kernel": ["linear", "poly", "rbf", "sigmoid"]
        #"SVR__degree": [1,2,3,5,8,10,15,20,30],
        #"SVR__gamma": ["auto", "scale"],
        #"SVR__coef0": [0, 1, 10, 100, 1000],
        #"SVR__C": [1,10,100,1000],
    }  
}    

model_param_dict["DT"] = {
    "estimator": Pipeline([('transformers', ct), ('DT', DecisionTreeRegressor())]),
    "params": {
        "DT__criterion": ["squared_error", "friedman_mse", "absolute_error", "poisson"],
        "DT__max_depth": [5, 10, 25, 50, 100, 1000],
        #add more hyperparameters...
        #https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor
    }  
}    

model_param_dict["RandomForestRegressor"] = {
    "estimator": Pipeline([('transformers', ct), ('RFR', RandomForestRegressor())]),
    "params": {
        "RFR__n_estimators": [1,5,10,20,50,100],
        "RFR__max_features": [1,5,10,20,50,100],
        #add more hyperparameters...
        #https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor
    }  
}    






model_param_dict

{'base': {'estimator': Pipeline(steps=[('transformers',
                   ColumnTransformer(remainder='passthrough',
                                     transformers=[('Location_One_Hot',
                                                    OneHotEncoder(handle_unknown='ignore'),
                                                    ['Location', 'City'])])),
                  ('LR', LinearRegression())]),
  'params': {}},
 'SVR': {'estimator': Pipeline(steps=[('transformers',
                   ColumnTransformer(remainder='passthrough',
                                     transformers=[('Location_One_Hot',
                                                    OneHotEncoder(handle_unknown='ignore'),
                                                    ['Location', 'City'])])),
                  ('SVR', SVR())]),
  'params': {'SVR__kernel': ['linear', 'poly', 'rbf', 'sigmoid']}},
 'DT': {'estimator': Pipeline(steps=[('transformers',
                   ColumnTransformer(remainder='passthrough',
                                     transformers=[('Location_One_Hot',
                                                    OneHotEncoder(handle_unknown='ignore'),
                                                    ['Location', 'City'])])),
                  ('DT', DecisionTreeRegressor())]),
  'params': {'DT__criterion': ['squared_error',
    'friedman_mse',
    'absolute_error',
    'poisson'],
   'DT__max_depth': [5, 10, 25, 50, 100, 1000]}},
 'RandomForestRegressor': {'estimator': Pipeline(steps=[('transformers',
                   ColumnTransformer(remainder='passthrough',
                                     transformers=[('Location_One_Hot',
                                                    OneHotEncoder(handle_unknown='ignore'),
                                                    ['Location', 'City'])])),
                  ('RFR', RandomForestRegressor())]),
  'params': {'RFR__n_estimators': [1, 5, 10, 20, 50, 100],
   'RFR__max_features': [1, 5, 10, 20, 50, 100]}}}

In [12]:
nested_cv_sklearnModels(model_param_dict, X_train, y_train)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4/4 [1:55:19<00:00, 1729.94s/it]

{'base': {'mean_fit_time': array([0.14878883]),
  'std_fit_time': array([0.01758362]),
  'mean_score_time': array([0.01286016]),
  'std_score_time': array([0.00188385]),
  'params': [{}],
  'split0_test_score': array([0.78840669]),
  'split1_test_score': array([0.77840797]),
  'split2_test_score': array([0.55922488]),
  'split3_test_score': array([0.6525055]),
  'split4_test_score': array([0.69268497]),
  'mean_test_score': array([0.694246]),
  'std_test_score': array([0.08476424]),
  'rank_test_score': array([1])},
 'SVR': {'mean_fit_time': array([5.90310349, 5.82982879, 5.9138515 , 6.3435709 ]),
  'std_fit_time': array([0.20627847, 0.3711414 , 0.04053663, 0.39070706]),
  'mean_score_time': array([1.13698707, 1.19201336, 1.25402927, 1.33376522]),
  'std_score_time': array([0.03076368, 0.15703678, 0.0172371 , 0.08768242]),
  'param_SVR__kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid'],
               mask=[False, False, False, False],
         fill_value='?',
              dtype=object),
  'params': [{'SVR__kernel': 'linear'},
   {'SVR__kernel': 'poly'},
   {'SVR__kernel': 'rbf'},
   {'SVR__kernel': 'sigmoid'}],
  'split0_test_score': array([ 0.34928036, -0.05646653, -0.06008694, -0.06012417]),
  'split1_test_score': array([ 0.37606256, -0.04774154, -0.05228972, -0.0523167 ]),
  'split2_test_score': array([ 0.41067414, -0.08204885, -0.08777801, -0.08780481]),
  'split3_test_score': array([ 0.44055226, -0.06905141, -0.07635457, -0.07641048]),
  'split4_test_score': array([ 0.2997722 , -0.04711402, -0.05055881, -0.05059237]),
  'mean_test_score': array([ 0.3752683 , -0.06048447, -0.06541361, -0.0654497 ]),
  'std_test_score': array([0.04876727, 0.01338439, 0.01443015, 0.01443237]),
  'rank_test_score': array([1, 2, 3, 4])},
 'DT': {'mean_fit_time': array([7.46329308e-02, 1.52594042e-01, 6.04194975e-01, 9.75466108e-01,
         1.07835717e+00, 9.47878456e-01, 4.94886875e-02, 1.38927507e-01,
         4.16588593e-01, 6.65398645e-01, 6.60850716e-01, 6.36815166e-01,
         6.64603166e+01, 6.86434723e+01, 7.13636263e+01, 7.29696859e+01,
         7.23468379e+01, 7.18166767e+01, 6.99184418e-02, 1.97029734e-01,
         8.98368549e-01, 8.47470045e-01, 8.41940784e-01, 8.34033585e-01]),
  'std_fit_time': array([9.79996504e-03, 1.21969410e-02, 1.48364925e-02, 1.43248229e-01,
         2.24083084e-01, 8.40331388e-02, 7.20311186e-03, 4.91028364e-02,
         4.89103281e-02, 1.80700777e-02, 2.31684170e-02, 1.87032462e-02,
         2.36294943e+01, 1.59529647e+00, 9.27837857e-01, 1.01676578e+00,
         1.29237303e+00, 1.26064834e+00, 3.38746622e-03, 1.80163979e-02,
         1.51665856e-01, 1.68856028e-01, 4.91919737e-02, 5.94686604e-02]),
  'mean_score_time': array([0.01952381, 0.01568246, 0.02091341, 0.01753354, 0.02078376,
         0.01360397, 0.01257124, 0.02125592, 0.01155539, 0.01297398,
         0.0113492 , 0.01281452, 0.01532688, 0.01591535, 0.01894312,
         0.01478729, 0.01703229, 0.01793685, 0.01587467, 0.01829982,
         0.02098961, 0.01449628, 0.01850471, 0.0158493 ]),
  'std_score_time': array([0.00276336, 0.00149461, 0.00441841, 0.00210326, 0.00542139,
         0.00180349, 0.00527062, 0.01057827, 0.00139782, 0.00114094,
         0.00139064, 0.00114085, 0.00214562, 0.00239724, 0.00477728,
         0.00195878, 0.00291917, 0.0015818 , 0.00227006, 0.00315933,
         0.00560611, 0.00190799, 0.00516359, 0.00217419]),
  'param_DT__criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                     'squared_error', 'squared_error', 'squared_error',
                     'friedman_mse', 'friedman_mse', 'friedman_mse',
                     'friedman_mse', 'friedman_mse', 'friedman_mse',
                     'absolute_error', 'absolute_error', 'absolute_error',
                     'absolute_error', 'absolute_error', 'absolute_error',
                     'poisson', 'poisson', 'poisson', 'poisson', 'poisson',
                     'poisson'],
               mask=[False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False],
         fill_value='?',
              dtype=object),
  'param_DT__max_depth': masked_array(data=[5, 10, 25, 50, 100, 1000, 5, 10, 25, 50, 100, 1000, 5,
                     10, 25, 50, 100, 1000, 5, 10, 25, 50, 100, 1000],
               mask=[False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False],
         fill_value='?',
              dtype=object),
  'params': [{'DT__criterion': 'squared_error', 'DT__max_depth': 5},
   {'DT__criterion': 'squared_error', 'DT__max_depth': 10},
   {'DT__criterion': 'squared_error', 'DT__max_depth': 25},
   {'DT__criterion': 'squared_error', 'DT__max_depth': 50},
   {'DT__criterion': 'squared_error', 'DT__max_depth': 100},
   {'DT__criterion': 'squared_error', 'DT__max_depth': 1000},
   {'DT__criterion': 'friedman_mse', 'DT__max_depth': 5},
   {'DT__criterion': 'friedman_mse', 'DT__max_depth': 10},
   {'DT__criterion': 'friedman_mse', 'DT__max_depth': 25},
   {'DT__criterion': 'friedman_mse', 'DT__max_depth': 50},
   {'DT__criterion': 'friedman_mse', 'DT__max_depth': 100},
   {'DT__criterion': 'friedman_mse', 'DT__max_depth': 1000},
   {'DT__criterion': 'absolute_error', 'DT__max_depth': 5},
   {'DT__criterion': 'absolute_error', 'DT__max_depth': 10},
   {'DT__criterion': 'absolute_error', 'DT__max_depth': 25},
   {'DT__criterion': 'absolute_error', 'DT__max_depth': 50},
   {'DT__criterion': 'absolute_error', 'DT__max_depth': 100},
   {'DT__criterion': 'absolute_error', 'DT__max_depth': 1000},
   {'DT__criterion': 'poisson', 'DT__max_depth': 5},
   {'DT__criterion': 'poisson', 'DT__max_depth': 10},
   {'DT__criterion': 'poisson', 'DT__max_depth': 25},
   {'DT__criterion': 'poisson', 'DT__max_depth': 50},
   {'DT__criterion': 'poisson', 'DT__max_depth': 100},
   {'DT__criterion': 'poisson', 'DT__max_depth': 1000}],
  'split0_test_score': array([0.76912678, 0.82644893, 0.85766238, 0.83298267, 0.83225036,
         0.83340041, 0.76912678, 0.82841465, 0.83911916, 0.82687637,
         0.83702246, 0.83904937, 0.7481649 , 0.86443723, 0.86786078,
         0.86461451, 0.86015938, 0.8652349 , 0.48626946, 0.51058609,
         0.82432802, 0.5191981 , 0.52646807, 0.52020236]),
  'split1_test_score': array([0.74307511, 0.72679153, 0.75181204, 0.78926202, 0.75824889,
         0.75096175, 0.74307511, 0.71281007, 0.78062785, 0.74703934,
         0.77853326, 0.76394903, 0.70895404, 0.82411571, 0.82879877,
         0.75861727, 0.761047  , 0.77052985, 0.75622783, 0.74167601,
         0.75198927, 0.7318263 , 0.79824125, 0.7364603 ]),
  'split2_test_score': array([ 0.50124733, -0.33739817, -0.29168422, -0.28904536,  0.06621507,
          0.54118568, -0.03377177,  0.11442946, -0.45729701, -0.29152292,
          0.53491539,  0.05801244,  0.5893829 ,  0.62419386,  0.51827688,
          0.63075801,  0.63667218,  0.64941608,  0.46409792,  0.48472877,
          0.11856222,  0.55445233,  0.62581466, -0.34034365]),
  'split3_test_score': array([0.55479506, 0.66849463, 0.68494935, 0.696878  , 0.5948179 ,
         0.7058091 , 0.55479506, 0.56689353, 0.61297272, 0.59162338,
         0.59305986, 0.61534548, 0.63249353, 0.82297832, 0.73804735,
         0.73505317, 0.60934524, 0.59990846, 0.58075546, 0.58895704,
         0.71452968, 0.70407234, 0.61402658, 0.69613717]),
  'split4_test_score': array([0.74450977, 0.73811662, 0.81896332, 0.81501531, 0.81591716,
         0.73670762, 0.67876643, 0.72791779, 0.81229058, 0.80658041,
         0.81353248, 0.81821001, 0.70205552, 0.74864816, 0.72106404,
         0.7093917 , 0.68377321, 0.78284604, 0.74382377, 0.77389134,
         0.74738886, 0.79518561, 0.79525562, 0.77138369]),
  'mean_test_score': array([0.66255081, 0.52449071, 0.56434057, 0.56901853, 0.61348988,
         0.71361291, 0.54239832, 0.5900931 , 0.51754266, 0.53611932,
         0.71141269, 0.61891327, 0.67621018, 0.77687466, 0.73480956,
         0.73968693, 0.7101994 , 0.73358707, 0.60623489, 0.61996785,
         0.63135961, 0.66094693, 0.67196124, 0.47676798]),
  'std_test_score': array([0.11152577, 0.4338963 , 0.43205113, 0.43158322, 0.28623294,
         0.09598895, 0.2974555 , 0.25205014, 0.49374505, 0.42195936,
         0.12318289, 0.29114839, 0.05721494, 0.08500898, 0.12134449,
         0.07585518, 0.09093914, 0.09599697, 0.12383247, 0.11808553,
         0.25889362, 0.10614852, 0.10751962, 0.41759294]),
  'rank_test_score': array([10, 22, 19, 18, 15,  5, 20, 17, 23, 21,  6, 14,  8,  1,  3,  2,  7,
          4, 16, 13, 12, 11,  9, 24])},
 'RandomForestRegressor': {'mean_fit_time': array([ 0.44582043,  1.90220337,  3.80703878,  8.29861569, 19.52102113,
         38.28362455,  0.39105043,  1.89997916,  3.72248564,  7.49822721,
         18.68241272, 36.79939752,  0.47517614,  1.71177917,  3.3931932 ,
          7.42673345, 17.89831486, 35.47006612,  0.3362155 ,  1.58352923,
          3.17508254,  6.49283614, 16.1245604 , 31.75471773,  0.30112114,
          1.34012094,  2.64056525,  5.25444832, 13.08963284, 26.69865465,
          0.26555734,  1.22251816,  2.36763005,  4.67687526, 11.99091225,
         23.75983534]),
  'std_fit_time': array([0.04919746, 0.02246955, 0.17485453, 0.3559262 , 0.83557961,
         0.64652645, 0.01376404, 0.02912159, 0.09928107, 0.2832218 ,
         0.42571029, 0.43857471, 0.15129431, 0.05098799, 0.12227578,
         0.20798313, 0.66516564, 0.43699232, 0.01711049, 0.04008092,
         0.06416426, 0.15818168, 0.33521456, 0.33503102, 0.01014031,
         0.03085626, 0.07424724, 0.06689063, 0.09054507, 0.14493662,
         0.02553649, 0.10187232, 0.03364742, 0.09151322, 0.70918756,
         0.91647464]),
  'mean_score_time': array([0.01985564, 0.02104907, 0.02798581, 0.04989939, 0.08468504,
         0.14610128, 0.01734071, 0.02034545, 0.02719064, 0.03884153,
         0.07104416, 0.13127294, 0.01840072, 0.0203063 , 0.02416005,
         0.04898248, 0.07053246, 0.12007365, 0.01461678, 0.0192059 ,
         0.02303514, 0.03523006, 0.06256347, 0.10985541, 0.0146173 ,
         0.02212977, 0.02132592, 0.03026214, 0.05869265, 0.1022584 ,
         0.01694331, 0.02840552, 0.0265038 , 0.03673239, 0.06190562,
         0.10293112]),
  'std_score_time': array([0.00524033, 0.00283668, 0.00300613, 0.00722456, 0.00244762,
         0.00457597, 0.00118249, 0.0025155 , 0.00200065, 0.00366715,
         0.00516404, 0.01048262, 0.0052351 , 0.00089965, 0.00247593,
         0.01626586, 0.00555039, 0.00569187, 0.00183707, 0.00159319,
         0.0015823 , 0.00298049, 0.00486536, 0.00345344, 0.00193483,
         0.00823364, 0.00303852, 0.00181947, 0.00318946, 0.00581591,
         0.0038631 , 0.01818682, 0.00295258, 0.0031961 , 0.00438937,
         0.00247152]),
  'param_RFR__max_features': masked_array(data=[1, 1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10,
                     10, 20, 20, 20, 20, 20, 20, 50, 50, 50, 50, 50, 50,
                     100, 100, 100, 100, 100, 100],
               mask=[False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False],
         fill_value='?',
              dtype=object),
  'param_RFR__n_estimators': masked_array(data=[1, 5, 10, 20, 50, 100, 1, 5, 10, 20, 50, 100, 1, 5, 10,
                     20, 50, 100, 1, 5, 10, 20, 50, 100, 1, 5, 10, 20, 50,
                     100, 1, 5, 10, 20, 50, 100],
               mask=[False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False, False, False, False, False,
                     False, False, False, False],
         fill_value='?',
              dtype=object),
  'params': [{'RFR__max_features': 1, 'RFR__n_estimators': 1},
   {'RFR__max_features': 1, 'RFR__n_estimators': 5},
   {'RFR__max_features': 1, 'RFR__n_estimators': 10},
   {'RFR__max_features': 1, 'RFR__n_estimators': 20},
   {'RFR__max_features': 1, 'RFR__n_estimators': 50},
   {'RFR__max_features': 1, 'RFR__n_estimators': 100},
   {'RFR__max_features': 5, 'RFR__n_estimators': 1},
   {'RFR__max_features': 5, 'RFR__n_estimators': 5},
   {'RFR__max_features': 5, 'RFR__n_estimators': 10},
   {'RFR__max_features': 5, 'RFR__n_estimators': 20},
   {'RFR__max_features': 5, 'RFR__n_estimators': 50},
   {'RFR__max_features': 5, 'RFR__n_estimators': 100},
   {'RFR__max_features': 10, 'RFR__n_estimators': 1},
   {'RFR__max_features': 10, 'RFR__n_estimators': 5},
   {'RFR__max_features': 10, 'RFR__n_estimators': 10},
   {'RFR__max_features': 10, 'RFR__n_estimators': 20},
   {'RFR__max_features': 10, 'RFR__n_estimators': 50},
   {'RFR__max_features': 10, 'RFR__n_estimators': 100},
   {'RFR__max_features': 20, 'RFR__n_estimators': 1},
   {'RFR__max_features': 20, 'RFR__n_estimators': 5},
   {'RFR__max_features': 20, 'RFR__n_estimators': 10},
   {'RFR__max_features': 20, 'RFR__n_estimators': 20},
   {'RFR__max_features': 20, 'RFR__n_estimators': 50},
   {'RFR__max_features': 20, 'RFR__n_estimators': 100},
   {'RFR__max_features': 50, 'RFR__n_estimators': 1},
   {'RFR__max_features': 50, 'RFR__n_estimators': 5},
   {'RFR__max_features': 50, 'RFR__n_estimators': 10},
   {'RFR__max_features': 50, 'RFR__n_estimators': 20},
   {'RFR__max_features': 50, 'RFR__n_estimators': 50},
   {'RFR__max_features': 50, 'RFR__n_estimators': 100},
   {'RFR__max_features': 100, 'RFR__n_estimators': 1},
   {'RFR__max_features': 100, 'RFR__n_estimators': 5},
   {'RFR__max_features': 100, 'RFR__n_estimators': 10},
   {'RFR__max_features': 100, 'RFR__n_estimators': 20},
   {'RFR__max_features': 100, 'RFR__n_estimators': 50},
   {'RFR__max_features': 100, 'RFR__n_estimators': 100}],
  'split0_test_score': array([0.18405412, 0.79890082, 0.78613657, 0.82613665, 0.822514  ,
         0.83457913, 0.68235641, 0.77076632, 0.78496595, 0.82841034,
         0.84630811, 0.83666534, 0.26787775, 0.79930042, 0.79151727,
         0.79471221, 0.84115501, 0.84258199, 0.70253649, 0.76142304,
         0.82966611, 0.84154323, 0.83934951, 0.84105582, 0.77555259,
         0.83848859, 0.82817756, 0.84697637, 0.85109761, 0.84774411,
         0.57388933, 0.80728784, 0.84151136, 0.84281648, 0.83881615,
         0.85233052]),
  'split1_test_score': array([ 0.62145534,  0.74300848,  0.78745702,  0.83081716,  0.83992773,
          0.8341412 ,  0.2479281 ,  0.75764567,  0.78471729,  0.81052465,
          0.82180226,  0.8147684 ,  0.50861088,  0.76879958,  0.8581214 ,
          0.86830012,  0.84534729,  0.8430697 ,  0.37298328,  0.86424068,
          0.82976031,  0.86015391,  0.82842866,  0.8596765 , -0.25160475,
          0.76995984,  0.8529343 ,  0.87140434,  0.84995676,  0.87749067,
          0.3708554 ,  0.89161285,  0.84044103,  0.80166548,  0.88736547,
          0.88179342]),
  'split2_test_score': array([0.39813448, 0.50795578, 0.60070693, 0.62686185, 0.62765726,
         0.64069338, 0.41739273, 0.47596174, 0.59975998, 0.63005282,
         0.64146724, 0.63435337, 0.37498552, 0.61218595, 0.64989057,
         0.62350766, 0.65471046, 0.64565459, 0.34117442, 0.6179528 ,
         0.62072907, 0.65923233, 0.66400279, 0.66023394, 0.49125561,
         0.59347707, 0.69420423, 0.66362867, 0.70183046, 0.67303978,
         0.51834338, 0.66241972, 0.69633329, 0.69958439, 0.71366102,
         0.70202231]),
  'split3_test_score': array([0.51135183, 0.68918472, 0.67378953, 0.75005962, 0.77107773,
         0.77917471, 0.49972174, 0.7241391 , 0.75315378, 0.75068756,
         0.77300546, 0.78312026, 0.68555659, 0.72025722, 0.73737964,
         0.77332487, 0.78292011, 0.79774564, 0.12557274, 0.73449386,
         0.76561288, 0.81072057, 0.78652385, 0.80276355, 0.16867551,
         0.77090486, 0.79811719, 0.76153549, 0.79038109, 0.80603293,
         0.33873519, 0.75530282, 0.79699871, 0.80321929, 0.79496318,
         0.81397332]),
  'split4_test_score': array([0.64176715, 0.74600444, 0.74424074, 0.76070774, 0.76743468,
         0.7824611 , 0.61960055, 0.75430194, 0.75470365, 0.76722692,
         0.78145216, 0.77795676, 0.27372104, 0.70279075, 0.77132315,
         0.7742645 , 0.77537285, 0.77965076, 0.62473832, 0.74677939,
         0.77920042, 0.78486495, 0.77756195, 0.78034948, 0.68391876,
         0.75104078, 0.79648032, 0.76818797, 0.77773461, 0.79101538,
         0.74514594, 0.77415507, 0.78495551, 0.77409872, 0.78188075,
         0.78563161]),
  'mean_test_score': array([0.47135258, 0.69701085, 0.71846616, 0.7589166 , 0.76572228,
         0.7742099 , 0.49339991, 0.69656296, 0.73546013, 0.75738046,
         0.77280704, 0.76937283, 0.42215036, 0.72066678, 0.76164641,
         0.76682187, 0.77990115, 0.78174054, 0.43340105, 0.74497795,
         0.76499376, 0.791303  , 0.77917335, 0.78881586, 0.37355955,
         0.74477423, 0.79398272, 0.78234657, 0.7942001 , 0.79906457,
         0.50939385, 0.77815566, 0.79204798, 0.78427687, 0.80333731,
         0.80715023]),
  'std_test_score': array([0.16797214, 0.10069835, 0.07192578, 0.07376766, 0.07459935,
         0.07093039, 0.15343052, 0.11135203, 0.06924594, 0.06960406,
         0.07089127, 0.07082651, 0.15805954, 0.06416826, 0.06836896,
         0.07963963, 0.06890219, 0.07244703, 0.20782597, 0.07841248,
         0.07667037, 0.0708882 , 0.06223848, 0.07007107, 0.37538819,
         0.08127682, 0.05408078, 0.07326091, 0.05507083, 0.07002278,
         0.14706195, 0.07436973, 0.05296155, 0.04767489, 0.05812371,
         0.06192633]),
  'rank_test_score': array([33, 29, 28, 22, 19, 15, 32, 30, 26, 23, 16, 17, 35, 27, 21, 18, 12,
         11, 34, 24, 20,  7, 13,  8, 36, 25,  5, 10,  4,  3, 31, 14,  6,  9,
          2,  1])}}